package com.example.demo.model;

import java.util.Calendar;
// default package
// Generated Sep 1, 2015 12:51:40 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * GptUser generated by hbm2java
 */

public class AdminUser implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	private static final long serialVersionUID = -8572231009389045184L;
	private Integer recordId;
	private String userId;
	private String firstName;
	private String lastName;
	private String password;
	private String emailId;
	private String isdCode;
	private String mobileNo;
	private int hierarchy;
	private String createdBy;
	private Date createdTime;
	private String modifiedBy;
	private Date modifiedTime;
	private String status;
	private String registrationType;
	private String pwdSessionKey;
	private String deviceId;
	private String osType;
	private String osVersion;
	private String appVersion;
	private String deviceModel;
	private String deviceToken;
	private String designation;
	private short unsuccessfulAttempt;
	private String paramName;
	private String paramValue;
	private String paramValue1;
	private String otp;
	private Date otpExpiryTime;
	private String officeAddress;

	public AdminUser() {
	}

	public AdminUser(String userId, String firstName, String password, String emailId, String mobileNo,
			String createdBy, Date createdTime, Date modifiedTime) {
		this.userId = userId;
		this.firstName = firstName;
		this.password = password;
		this.emailId = emailId;
		this.mobileNo = mobileNo;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
	}

	public AdminUser(String userId, String firstName, String lastName, String password, String emailId, String mobileNo,
			int hierarchy, String createdBy, Date createdTime, String modifiedBy, Date modifiedTime, String status) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.emailId = emailId;
		this.mobileNo = mobileNo;
		this.hierarchy = hierarchy;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.modifiedBy = modifiedBy;
		this.modifiedTime = modifiedTime;
		this.status = status;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getIsdCode() {
		return isdCode;
	}

	public void setIsdCode(String inIsdCode) {
		isdCode = inIsdCode;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public int getHierarchy() {
		return this.hierarchy;
	}

	public void setHierarchy(int hierarchy) {
		this.hierarchy = hierarchy;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedTime() {
		if (null == modifiedTime) {
			this.modifiedTime = Calendar.getInstance().getTime();
		}
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRegistrationType() {
		return registrationType;
	}

	public void setRegistrationType(String inRegistrationType) {
		registrationType = inRegistrationType;
	}

	public String getPwdSessionKey() {
		return pwdSessionKey;
	}

	public void setPwdSessionKey(String inPwdSessionKey) {
		pwdSessionKey = inPwdSessionKey;
	}

	public String getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(String inDeviceId) {
		deviceId = inDeviceId;
	}

	public String getOsType() {
		return osType;
	}

	public void setOsType(String inOsType) {
		osType = inOsType;
	}

	public String getOsVersion() {
		return osVersion;
	}

	public void setOsVersion(String inOsVersion) {
		osVersion = inOsVersion;
	}

	public String getAppVersion() {
		return appVersion;
	}

	public void setAppVersion(String inAppVersion) {
		appVersion = inAppVersion;
	}

	public String getDeviceModel() {
		return deviceModel;
	}

	public void setDeviceModel(String inDeviceModel) {
		deviceModel = inDeviceModel;
	}

	public String getDeviceToken() {
		return deviceToken;
	}

	public void setDeviceToken(String inDeviceToken) {
		deviceToken = inDeviceToken;
	}

	public String getDesignation() {
		return designation;
	}

	public void setDesignation(String inDesignation) {
		designation = inDesignation;
	}

	public short getUnsuccessfulAttempt() {
		return unsuccessfulAttempt;
	}

	public void setUnsuccessfulAttempt(short inUnsuccessfulAttempt) {
		unsuccessfulAttempt = inUnsuccessfulAttempt;
	}

	public String getParamName() {
		return paramName;
	}

	public void setParamName(String inParamName) {
		paramName = inParamName;
	}

	public String getParamValue() {
		return paramValue;
	}

	public void setParamValue(String inParamValue) {
		paramValue = inParamValue;
	}

	public String getParamValue1() {
		return paramValue1;
	}

	public void setParamValue1(String inParamValue1) {
		paramValue1 = inParamValue1;
	}

	public String getOtp() {
		return otp;
	}

	public void setOtp(String inOtp) {
		otp = inOtp;
	}

	public Date getOtpExpiryTime() {
		return otpExpiryTime;
	}

	public void setOtpExpiryTime(Date inOtpExpiryTime) {
		otpExpiryTime = inOtpExpiryTime;
	}

	public String getOfficeAddress() {
		return officeAddress;
	}

	public void setOfficeAddress(String inOfficeAddress) {
		officeAddress = inOfficeAddress;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("AdminUser [recordId=").append(recordId).append(", userId=").append(userId)
				.append(", firstName=").append(firstName).append(", lastName=").append(lastName).append(", password=")
				.append(password).append(", emailId=").append(emailId).append(", isdCode=").append(isdCode)
				.append(", mobileNo=").append(mobileNo).append(", hierarchy=").append(hierarchy).append(", createdBy=")
				.append(createdBy).append(", createdTime=").append(createdTime).append(", modifiedBy=")
				.append(modifiedBy).append(", modifiedTime=").append(modifiedTime).append(", status=").append(status)
				.append(", registrationType=").append(registrationType).append(", pwdSessionKey=").append(pwdSessionKey)
				.append(", deviceId=").append(deviceId).append(", osType=").append(osType).append(", osVersion=")
				.append(osVersion).append(", appVersion=").append(appVersion).append(", deviceModel=")
				.append(deviceModel).append(", deviceToken=").append(deviceToken).append(", designation=")
				.append(designation).append(", unsuccessfulAttempt=").append(unsuccessfulAttempt).append(", paramName=")
				.append(paramName).append(", paramValue=").append(paramValue).append(", paramValue1=")
				.append(paramValue1).append(", otp=").append(otp).append(", otpExpiryTime=").append(otpExpiryTime)
				.append("]");
		return builder.toString();
	}
}
